### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Zombar3** [NRGDEAD/Cue2cu2#3] opened 2022-04-18 14:21 UTC
A year ago i made images and Cue2cu2 working perfectly, but now it give me a error.
What am i doing wrong?
\cue2cu2.py", line 95
    print("Cue2cu2: Error while processing "+cuesheet+": "+message+".", file=sys.stderr)
                                                                            ^
SyntaxError: invalid syntax

**Comment by NRGDEAD** [comment] 2022-04-19 08:37
That's odd. Can you tell me what Python version you're running and the operating system? Also, can you please attach the cue sheet here and tell me the image file's file size in bytes (not to be confused with the "size on disk")?

**Comment by Zombar3** [comment] 2022-04-22 06:29
This error appears regardless of the file.

Python 2.7, 3.9.4, Window 10 64bit.  size 633 445 344 
[crisis_city.zip](https://github.com/NRGDEAD/Cue2cu2/files/8537491/crisis_city.zip)

**Comment by NRGDEAD** [comment] 2022-04-23 14:35
I get the same error on Python 2.7.18 on Linux. But my default Python 3.10.4 successfully converted the cue sheet. So I assume you have Python 2 set as default and Windows ignores the shebang requesting python3. If you change the default or run the script explicitly with python3, does it still produce this error?

**Comment by Zombar3** [comment] 2022-05-07 18:06
Ok. I delete 2.7 and now don't see .cue.
cue2cu2.py: error: the following arguments are required: cuesheet

**Comment by NRGDEAD** [comment] 2022-05-10 07:43
That means that no cue sheet was provided to be converted. Are you using the proper parameters? For example: `cue2cu2.py crisis_city.cue`…

**Comment by Zombar3** [comment] 2022-05-10 17:40
I need the old format cu2. Only your program works.
E:\Games\PS1\Crisis_City>cue2cu2.py -f 1 crisis_city.cue
usage: cue2cu2.py [-h] [-c] [-nc] [-f FORMAT] [-s SIZE] [-n NAME] [-o OFFSET] [-os OFFSET_SELECT] [-1] [-q] cuesheet
cue2cu2.py: error: the following arguments are required: cuesheet

**Comment by NRGDEAD** [comment] 2022-05-28 00:06
I have just installed the current Version of Python, 3.10.4, in an up-to-date (as of last month) Windows 10 VM and could not reproduce the error. Neither with format 1 or 2.

```
PS C:\Users\NRG\Desktop\Cue2cu2-master> python -V
Python 3.10.4
PS C:\Users\NRG\Desktop\Cue2cu2-master> python .\cue2cu2.py -f 1 --size 633445344 crisis_city.cue
PS C:\Users\NRG\Desktop\Cue2cu2-master> cat .\crisis_city.cu2
ntracks 15
size      59:52:72
data1     00:02:00
track02   29:11:39
track03   30:53:24
```

I would suggest you try (re-)installing the latest Python 3, downloading the latest cue2cu2 from this repository, and try again.

---
<sup>PS and on another note: I would further suggest updating your PSIO; the versions using the newer format CU2 sheets have quite a few improvements.</sup>

**Comment by NRGDEAD** [comment] 2022-06-10 12:17
I'm gonna close this since I can't reproduce the error and have received no feedback after two weeks. If you still need help, I can probably re-open this, please let me know.

**Closed as not planned by NRGDEAD** 2022-06-10 12:17 UTC
